# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ScSQKnIQgaISCyLgbGCqLw38yiq7M8l1
"""

import streamlit as st
import requests
import datetime
import pandas as pd

# 설정
st.set_page_config(page_title="피부 보호 AI", layout="centered")
st.title("🌤️ AI 기반 맞춤형 피부 보호 프로그램")

# 기상청 API 인증키 (테스트용)
API_KEY = "rE1UBiTAA83Ww7niPLiHVd2PNvxEpqDERG8Ore1kHCy9GnAMgccbVW4m0hifrh7UlhqZ13ezac9fo5nL8%2Bh%2F4Q%3D%3D"

# 현재 날짜와 시간 설정
def get_base_time():
    now = datetime.datetime.now()
    if now.minute < 45:
        now = now - datetime.timedelta(hours=1)
    return now.strftime("%Y%m%d"), now.strftime("%H00")

# 기상청 API에서 날씨 불러오기
def get_weather():
    base_date, base_time = get_base_time()
    url = "https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst"
    params = {
        "serviceKey": API_KEY,
        "pageNo": "1",
        "numOfRows": "100",
        "dataType": "JSON",
        "base_date": base_date,
        "base_time": base_time,
        "nx": "57",  # 광명시 위치
        "ny": "126"
    }
    response = requests.get(url, params=params, timeout=10)
    if response.status_code == 200:
        return response.json()
    return None

# 날씨 데이터 → 피부 조건 분류
def interpret_weather(data):
    condition = []
    items = data['response']['body']['items']['item']
    for item in items:
        if item['category'] == 'T1H':
            temp = float(item['obsrValue'])
            if temp < 10:
                condition.append('추움')
            elif temp > 27:
                condition.append('더움')
        elif item['category'] == 'REH':
            reh = float(item['obsrValue'])
            if reh < 40:
                condition.append('건조함')
            elif reh > 75:
                condition.append('습함')
        elif item['category'] == 'UV':
            uv = float(item['obsrValue'])
            if uv > 7:
                condition.append('자외선 강함')
    return condition

# 추천 성분 매핑
recommendation_db = pd.DataFrame([
    {"status": "추움", "ingredient": "세라마이드", "effect": "보습, 장벽 강화"},
    {"status": "더움", "ingredient": "살리실산", "effect": "모공 피지 용해"},
    {"status": "건조함", "ingredient": "히알루론산", "effect": "수분 유지"},
    {"status": "자외선 강함", "ingredient": "자외선 차단제 SPF50+", "effect": "광노화 방지"},
])

# 날씨 가져오기
if st.button("🔄 날씨 새로고침"):
    st.rerun()

weather_data = get_weather()
if weather_data:
    st.success("✅ 날씨 정보를 성공적으로 불러왔어요!")
    conditions = interpret_weather(weather_data)
    st.subheader("🌡️ 감지된 피부 환경:")
    for cond in conditions:
        st.write(f"- {cond}")

    st.subheader("🧴 추천 성분:")
    for cond in conditions:
        row = recommendation_db[recommendation_db['status'] == cond]
        if not row.empty:
            st.write(f"**{cond}**")
            st.write(f"- 성분: {row['ingredient'].values[0]}")
            st.write(f"- 효과: {row['effect'].values[0]}")
else:
    st.warning("❗ 날씨 데이터를 불러올 수 없습니다. 다시 시도해보세요.")